version: '3'

services:
  api-solid-pg:
    image: bitnamilegacy/postgresql:latest
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: apisolid
    volumes:
      - pgdata:/bitnami/postgresql

volumes:
  pgdata:
